### ISSUE TITLE
How to improve result?

### ISSUE THREAD

**Issue by hardikdava** [wanmeihuali/taichi_3d_gaussian_splatting#131]
Hello @wanmeihuali , I have started doing some experiments with the code. The implementation is really good and clean, I like it. I have couple of questions regarding result quality.

- Result is a bit blur and missing some fine details.
- Because of black ground PSNR and SSIM score look good.
- 
Left = Rendered View, Right = Groundtruth View
<img width="685" alt="Screenshot 2023-09-29 134311" src="https://github.com/wanmeihuali/taichi_3d_gaussian_splatting/assets/39372750/71e65407-39e6-4f56-83af-da9d8f75683c">

**Questions:**
- Which parameter affeacts for image sharpness?
- Is it possible to know a little description of parameters? 
- Can we use RayTune or Optuna tool to get tunned parameters?

**Comment by wanmeihuali** [comment]
Hi @hardikdava , there could be a lot of parameters that affect image sharpness, Given this is your private dataset, I can only provide some ideas:
- input camera pose; inaccurate camera pose reduces the quality of training.
- input images; make sure your image is undistorted and the resolution isn't too low.
- input pointcloud; try to provide a more dense input point cloud, or choose a more radical densify policy.
- densify policy: 
```yaml
adaptive-controller-config:
  # The threshold on the gradient of point position in the camera plane for all affected pixels
  # decrease it->more points, slower train/render speed, better quality
  densification-view-space-position-gradients-threshold: 6e-6 
# The frequency to split/clone points, shall adjust base on dataset size
  num-iterations-densify: 100
# The frequency to reset all point opacity, if you have more images, maybe you shall increase this value, otherwise points may still be transparent. Also, please note that rendering quality will drop dramatically in the few iterations after reset.
  num-iterations-reset-alpha: 4000
```
About autotuning tools: sure, you can try to find the best parameters in the YAML config.
